"""add last login column

Revision ID: bf48745fb4ee
Revises: ef5591be0076
Create Date: 2021-09-02 15:02:38.812307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf48745fb4ee'
down_revision = 'ef5591be0076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_login')
    # ### end Alembic commands ###
